# Site settings
title: "Brian Bunke"
email: me@brianbunke.com
description: "...And You Will Know Me by the Trail of Documentation"
baseurl: ""
url: "https://brianbunke.github.io"
title_description: "Systems Automator in the Seattle area. I often write about PowerShell and VMware. My son thinks I'm funny.
<br><br>
<a href=\"/blog/2017/07/23/it-ops-manifesto-2017/\">2017 Manifesto</a> | <a href=\"/blog/2017/05/08/github-101/\">GitHub 101</a> | <a href=\"/blog/2017/03/07/introducing-vester/\">Vester</a> | <a href=\"https://atlassianps.org/\">ConfluencePS</a>"
title_image: "https://brianbunke.github.io/images/brian.jpg"
google_analytics: "UA-59218526-2"
github_repository: https://github.com/brianbunke/brianbunke.github.io
post_limit: 5
# disqus_account: insert-here
# addthis_id: insert-here

# Social usernames/URLs
twitter_username: brianbunke
github_username:  brianbunke
reddit_username:  brianbunke
linkedin_link:    brianbunke
instagram_username: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "<a href=\"https://jekyllrb.com\">Jekyll</a> | <a href=\"https://pages.github.com\">GitHub Pages</a> | <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>"
footer_right: "<a href=\"https://github.com/brianbunke/brianbunke.github.io\"><i class=\"fa fa-code\"></i><i class=\"fa fa-github\"></i></a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
future: false
